# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/sso/sso.proto --js_out=import_style=commonjs,binary:gen/js/ --plugin=protoc-gen-js=../protobuf-javascript-3.21.4-win64/bin/protoc-gen-js.exe --grpc-web_out=import_style=commonjs,mode=grpcwebtext:gen/js/
